databases:
  - name: database
    databaseName: foil
    plan: pro-4gb

services:
  - name: web-service
    type: web
    env: node
    plan: pro
    buildCommand: npm install -g pnpm@9 && bash render-build-sdk.sh
    startCommand: pnpm --filter @sapience/api start:service
    autoDeploy: true
    repo: https://github.com/sapiencexyz/sapience
    branch: main
    buildFilter:
      paths:
        - packages/api/**
        - packages/sdk/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString

  - name: background-worker
    type: worker
    env: node
    plan: standard
    buildCommand: npm install -g pnpm@9 && bash render-build-sdk.sh && pnpm --filter @sapience/api prisma:generate
    startCommand: pnpm --filter @sapience/api start:worker
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - packages/api/**
        - packages/sdk/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString

  - name: relayer-ws
    type: web
    env: node
    plan: standard
    buildCommand: npm install -g pnpm@9 && bash render-build-sdk.sh
    startCommand: pnpm --filter @sapience/relayer start
    autoDeploy: true
    repo: https://github.com/sapiencexyz/sapience
    branch: main
    buildFilter:
      paths:
        - packages/relayer-ws/**
    envVars:
      - key: ENABLE_AUCTION_WS
        value: "true"
